FROM resin/armv7hf-debian-qemu

RUN [ "cross-build-start" ]

RUN apt-get update && apt-get install -qq -y \
	build-essential \
	patch \
	ruby-dev \
	zlib1g-dev \
	liblzma-dev \
	bash \
	cron \
 	vim \
&& rm -rf /var/lib/apt/lists/*

RUN mkdir /files
VOLUME /files

WORKDIR /root
COPY Gemfile .
COPY Gemfile.lock .
RUN gem install bundler
RUN bundle
ADD . .

RUN [ "cross-build-end" ]

CMD ruby /root/gdrive_sync.rb