FROM mastermindg/docker-rpi-ruby

RUN [ "cross-build-start" ]

RUN mkdir /files
VOLUME /files

WORKDIR /root
COPY Gemfile .
COPY Gemfile.lock .
RUN gem install bundler
RUN bundle install

RUN [ "cross-build-end" ]

CMD ruby /root/gdrive_sync.rb